package view;
import controllers.MainMenuController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cmb6094
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    GameButton newGameButton;
    GameButton optionsButton;
    GameButton quitButton;
    JPanel buttonPanel;
    MainMenuController controller;
    public MainMenu() {
        initComponents();
        this.controller = controller;
        newGameButton = new GameButton(new File(".//NewGame.png"));
        optionsButton = new GameButton(new File(".//Options.png"));
        quitButton = new GameButton(new File(".//Quit.png"));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));
        
       // buttonPanel.setOpaque(false);
        //buttonPanel.setBackground(Color.red);
        buttonPanel.add(newGameButton);
        buttonPanel.add(optionsButton);
        buttonPanel.add(quitButton);
        buttonPanel.setVisible(true);
        this.setLayout(new BorderLayout());
        this.add(buttonPanel, BorderLayout.EAST);
        
    }
    // 333 x 124
    public void addNewGameButtonController(MouseAdapter adapter){
        newGameButton.addMouseListener(adapter);
    }
    public void addOptionsButtonController(MouseAdapter adapter){
        optionsButton.addMouseListener(adapter);
    }
    public void addQuitButtonController(MouseAdapter adapter){
        quitButton.addMouseListener(adapter);
    }
    public GameButton getNewGameButton(){
        return newGameButton;
    }
    public GameButton getOptionsButton(){
        return optionsButton;
    }
    public GameButton getQuitButton(){
        return quitButton;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
